name: open-webui-dev

services:
  frontend:
    build:
      context: .
      target: build
    command: ["sh", "/app/src/frontend-dev.sh"]
    env_file: ".env"
    env:
      - NODE_OPTIONS=--max-old-space-size=3300
    depends_on:
      - backend
    ports:
      - "3000:5173"
    extra_hosts:
      - host.docker.internal:127.0.0.1
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./static/assets:/app/static/assets
      - ./static/avatars:/app/static/avatars
      - ./static/data:/app/static/data
      - ./static/favicon:/app/static/favicon
      - ./static/static:/app/static/static
      - ./vite.config.ts:/app/vite.config.ts
      - ./svelte.config.js:/app/svelte.config.js
      - ./tsconfig.json:/app/tsconfig.json
      - ./tsconfig.ionos.json:/app/tsconfig.ionos.json
      - ./tailwind.config.js:/app/tailwind.config.js

  backend:
    build:
      context: .
      target: base
    command: ["bash", "dev.sh"]
    env_file: ".env"
    environment:
      - ENV=dev
    ports:
      - "8080:8080"
    extra_hosts:
      - host.docker.internal:127.0.0.1
    volumes:
      - ./backend:/app/backend
      - data:/app/backend/data

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.7-0
    command: ["start-dev", "--http-enabled=true", "--http-port=8079", "--log-level=info", "--import-realm"]
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    environment:
      # Needed to create a config from scratch. Causing errors when using --import-realm
      # - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      # - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_FEATURES=persistent-user-sessions
    network_mode: host
    ports:
      - "8079:8079"
 
volumes:
  data: {}
