services:
  ollama:
    volumes:
      - ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}

  open-webui:
    build:
      context: .
      args:
        OLLAMA_BASE_URL: '/ollama'
      dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY='
      - OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID} # Lade aus .env
      - OAUTH_CLIENT_SECRET=${OAUTH_CLIENT_SECRET} # Lade aus .env
      - OAUTH_TENANT_ID=${OAUTH_TENANT_ID} # Lade aus .env
      # Füge hier alle anderen OAUTH_* Variablen hinzu, die du aus .env laden möchtest
      - OAUTH_AUTHORIZATION_URL=${OAUTH_AUTHORIZATION_URL}
      - OAUTH_TOKEN_URL=${OAUTH_TOKEN_URL}
      - OAUTH_USERINFO_URL=${OAUTH_USERINFO_URL}
      - OAUTH_JWKS_URL=${OAUTH_JWKS_URL}
      - OAUTH_SCOPES=${OAUTH_SCOPES}
      - OAUTH_REDIRECT_URI=${OAUTH_REDIRECT_URI}
      - WEBUI_AUTH_METHOD=${WEBUI_AUTH_METHOD}
      - WEBUI_SSO_ONLY=${WEBUI_SSO_ONLY}
      #- OAUTH_GROUPS_CLAIM=${OAUTH_GROUPS_CLAIM}
      #- OAUTH_ADMIN_GROUP_ID=${OAUTH_ADMIN_GROUP_ID}
    env_file:
      - .env
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  ollama: {}
  open-webui: {}
