services:
  ollama:
    volumes:
      - ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}

  open-webui:
    build:
      context: .
      args:
        OLLAMA_BASE_URL: '/ollama'
      dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY='
      - OAUTH_CLIENT_ID=8b2f69c8-c78e-4ff0-9869-d1a7ea677eef
      - OAUTH_CLIENT_SECRET=L5D8Q~pHe6l5QvvSlCtm-Bqz3t6dgDmy4fcWJdhf
      - OAUTH_TENANT_ID=07502144-65bd-4e15-90fc-b56798f45494
      - OAUTH_AUTHORIZATION_URL=https://login.microsoftonline.com/07502144-65bd-4e15-90fc-b56798f45494/oauth2/v2.0/authorize
      - OAUTH_TOKEN_URL=https://login.microsoftonline.com/07502144-65bd-4e15-90fc-b56798f45494/oauth2/v2.0/token
      - OAUTH_USERINFO_URL=https://graph.microsoft.com/oidc/userinfo
      - OAUTH_JWKS_URL=https://login.microsoftonline.com/07502144-65bd-4e15-90fc-b56798f45494/discovery/v2.0/keys
      - OAUTH_SCOPES="openid profile email"
      - OAUTH_REDIRECT_URI=http://localhost:8080/oauth # Oder deine Produktions-URL
      - WEBUI_AUTH_METHOD=oauth
      - WEBUI_SSO_ONLY=True
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  ollama: {}
  open-webui: {}
