apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: andy-axcel-ia
  name: andy-axcel-ia-pvc
  namespace: andy-axcel-ia
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 2Gi